name: anomaly

services:
  sae-anomaly-detection:
    image: ${PRIVATE_IMAGE_REGISTRY}/sae-anomaly-detection:${ANOMALY_DETECTION_VERSION}
    volumes:
      - ./sae-anomaly-detection/sae-anomaly-detection.settings.yaml:/code/settings.yaml

  anomaly-post-processor:
    image: ${PRIVATE_IMAGE_REGISTRY}/anomaly-post-processing:${ANOMALY_POST_PROCESSING_VERSION}
    volumes:
      - ./anomaly-post-processing/anomaly-post-processing.settings.yaml:/code/settings.yaml

networks:
  default:
    name: sae
    external: true
