[tool.poetry]
name = "anomalydetection"
version = "0.1.0"
description = ""
authors = ["flonix8 <flstanek@googlemail.com>"]
license = "AGPLv3"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pydantic = "^2.0.0"
torch = "^2.3.1"
numpy = "^1.26.4"
visionapi = { git = "https://github.com/starwit/vision-api.git", subdirectory = "python/visionapi", tag = "3.0.0" }
visionlib = { git = "https://github.com/starwit/vision-lib.git", subdirectory = "python", tag = "0.10.0" }
aesanomalydetection = { git = "https://github.com/starwit/ae-trajectories.git", branch = "main" }
redis = "^5.0.0"
pydantic-settings = "^2.0.3"
prometheus-client = "^0.17.1"
opencv-python = "^4.10.0.84"
tqdm = "^4.66.4"
matplotlib = "^3.9.0"
scipy = "^1.14.0"
tomlkit = "^0.13.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
