[tool.poetry]
package-mode = false
name = "anomalydetection"
version = "0.3.1"
description = ""
authors = ["flonix8 <flstanek@googlemail.com>"]
license = "AGPLv3"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pydantic = "^2.10.6"
torch = "^2.6.0"
numpy = "^1.26.4"
visionapi = { git = "https://github.com/starwit/vision-api.git", subdirectory = "python/visionapi", tag = "3.1.0" }
visionlib = { git = "https://github.com/starwit/vision-lib.git", subdirectory = "python", tag = "0.11.2" }
movementpredictor = { git = "https://github.com/starwit/movement-predictor.git", branch = "main", tag = "0.1.1" }
redis = "^5.0.0"
pydantic-settings = "^2.8.1"
prometheus-client = "0.21.1"
opencv-python = "^4.11.0.86"
tqdm = "^4.66.4"
matplotlib = "^3.10.1"
scipy = "^1.15.2"
tomlkit = "^0.13.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
