log_level: DEBUG
redisIn:
  host: localhost
  port: 6379
  stream_id: stream1
  stream_prefix: objecttracker
redisOut:
  host: localhost
  port: 6379
  stream_id: stream1
  stream_prefix: anomalydetection
filtering: True
model:
  anomaly_threshold_override:           # only for testing:  remove if not testing     
  parameters_path: model/parameters.json
  weights_path: model/model_weights.pth
  background_path: model/frame.pth
prometheus_port: 8000