log_level: DEBUG
redis:
  host: redis
  port: 6379
  stream_id: stream1
  input_stream_prefix: objecttracker
  output_stream_prefix: anomalydetection
filtering: True
model:
  anomaly_loss_threshold: 0.8
  parameters_path: model/parameters.json
  weights_path: model/best_model_weights_8dim.pth
prometheus_port: 8000