log_level: DEBUG
redis:
  host: redis
  port: 6379
  stream_id: stream1
  input_stream_prefix: objecttracker
  output_stream_prefix: anomalydetection
prometheus_port: 8000
path_to_model_config: /home/hanna/workspaces/AETrajectories/AEsAnomalyDetection/RecurrentAE/parameters.json