{{- with .Values.anomalyDetection }}
{{- $imageRepo := required "image repository for anomaly-detection is required" .image.repository }}
{{- $imageTag := required "image tag for anomaly-detection is required" .image.tag }}
{{- $config := . }}
{{- $streamId := .stream_id -}}
{{- $instanceName := printf "anomaly-detection-%s" (lower .) }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "fullname" $ }}-{{ $instanceName }}
  labels:
    {{- include "labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $instanceName }}
spec:
  selector:
    matchLabels:
      {{- include "selectorLabels" $ | nindent 6 }}
      app.kubernetes.io/component: {{ $instanceName }}
  template:
    metadata:
      annotations:
        starwit.de/stage: anomaly-detection
      labels:
        {{- include "selectorLabels" $ | nindent 8 }}
        app.kubernetes.io/component: {{ $instanceName }}
    spec:
      serviceAccountName: {{ include "serviceAccountName" $ }}
      securityContext:
        {{- toYaml $.Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ $instanceName }}
          securityContext:
            {{- toYaml $.Values.securityContext | nindent 12 }}
          image: "{{ $imageRepo }}:{{ $imageTag }}"
          imagePullPolicy: IfNotPresent
          env:
            - name: LOG_LEVEL
              value: {{ $config.logLevel | quote }}
            - name: REDIS__STREAM_ID
              value: {{ $streamId | quote }}
          ports:
            - name: prometheus
              containerPort: 8000
          volumeMounts:
            - name: config
              mountPath: /code/settings.yaml
              subPath: settings.yaml
      volumes:
        - name: config
          configMap:
            name: anomaly-detection-config
      {{- with $.Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
{{- end }}
{{- end }}
