{{- with .Values.anomalyPostProcessing }}
{{- $imageRepo := required "image repository for anomaly-post-processing is required" .image.repository }}
{{- $imageTag := required "image tag for anomaly-post-processing is required" .image.tag }}
{{- $config := . }}
{{- $streamId := .stream_id -}}
{{- $instanceName := printf "anomaly-post-processing-%s" (lower .) }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "ande.fullname" $ }}-{{ $instanceName }}
  labels:
    {{- include "ande.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $instanceName }}
spec:
  selector:
    matchLabels:
      {{- include "ande.selectorLabels" $ | nindent 6 }}
      app.kubernetes.io/component: {{ $instanceName }}
  template:
    metadata:
      annotations:
        ande.starwit.de/stage: anomaly-post-processing
      labels:
        {{- include "ande.selectorLabels" $ | nindent 8 }}
        app.kubernetes.io/component: {{ $instanceName }}
    spec:
      serviceAccountName: {{ include "ande.serviceAccountName" $ }}
      securityContext:
        {{- toYaml $.Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: wait-for-redis
          image: valkey/valkey:7.2.6-alpine
          command: ["sh", "-c", "while ! redis-cli -h {{ include "sae.redisServiceName" $ }} ping ; do echo \"$(date -Iseconds) - still waiting for redis\"; sleep 1; done"]
          command: ["sh", "-c", "while ! redis-cli -h {{ include "ande.redisServiceName" $ }} ping ; do echo \"$(date -Iseconds) - still waiting for redis\"; sleep 1; done"]
      containers:
        - name: {{ $instanceName }}
          securityContext:
            {{- toYaml $.Values.securityContext | nindent 12 }}
          image: "{{ $imageRepo }}:{{ $imageTag }}"
          imagePullPolicy: IfNotPresent
          env:
            - name: LOG_LEVEL
              value: {{ $config.logLevel | quote }}
            - name: REDIS__HOST
              value: {{ include "ande.redisServiceName" $ }}
            - name: REDIS__PORT
              value: {{ include "ande.redisServicePort" $ }}
            - name: REDIS__STREAM_ID
              value: {{ $streamId | quote }}
          ports:
            - name: prometheus
              containerPort: 8000
          volumeMounts:
            - name: config
              mountPath: /code/settings.yaml
              subPath: settings.yaml
      volumes:
        - name: config
          configMap:
            name: anomaly-post-processing-config
      {{- with $.Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
{{- end }}
{{- end }}
