name: docker-internal build and push

on:
  workflow_dispatch:

permissions: read-all

jobs:
  build:
    name: "Build and run docker image"
    runs-on: [self-hosted, linux, X64]

    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: checkout
      uses: actions/checkout@v4

    - name: Login internal docker registry
      uses: docker/login-action@v3
      with:
        registry: docker.internal.starwit-infra.de
        username: ${{ secrets.DOCKER_INTERNAL_USERNAME }}
        password: ${{ secrets.DOCKER_INTERNAL_PASSWORD }}

    - name: build docker
      env:
        GIT_CREDENTIALS: https://starwit:${{ secrets.VISION_PIPELINE_READ_TOKEN }}@github.com
      run: |
        docker build --secret id=GIT_CREDENTIALS -t docker.internal.starwit-infra.de/sae-anomaly-detection:tmp .

    - name: push docker latest and versioned
      run: |
        DOCKER_VERSION=$(cat pyproject.toml | grep "version" | cut -d'=' -f2 | xargs echo -n)
        docker tag docker.internal.starwit-infra.de/sae-anomaly-detection:tmp docker.internal.starwit-infra.de/sae-anomaly-detection:$DOCKER_VERSION
        docker push docker.internal.starwit-infra.de/sae-anomaly-detection:$DOCKER_VERSION
