name: docker build

on:
  workflow_dispatch:

jobs:
  build:
    name: "Build and run docker image"
    runs-on: [self-hosted, linux, X64]

    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - run: echo "GIT_CREDENTIALS=https://${{ secrets.GITHUB_USER }}:${{ secrets.GITHUB_TOKEN }}@github.com" >> $GITHUB_ENV
    - run: docker build --secret id=${{ env.GIT_CREDENTIALS }} -t starwitorg/sae-anomaly-detection:latest .
